#ifndef ROBOTINTERFACE_WRAPPER_H_
#define ROBOTINTERFACE_WRAPPER_H_
#ifdef BUILD_REAL_ROBOT
#include "urrobot/ur5/control_box_driver/ur_c_api/robotinterface.h"
/******************************build with real robotinterface functions******************************/
#define  wrapper_robotinterface_get_step()                                                                                         robotinterface_get_step()
#define  wrapper_robotinterface_get_time()                                                                                         robotinterface_get_time()
#define  wrapper_robotinterface_get_time_per_step()                                                                                robotinterface_get_time_per_step()
#define  wrapper_robotinterface_command_position_velocity_acceleration(q, qd, qdd)                                                 robotinterface_command_position_velocity_acceleration(q, qd, qdd)
#define  wrapper_robotinterface_command_velocity_acceleration(q, qd, qdd)                                                          robotinterface_command_velocity_acceleration(q, qd, qdd)
#define  wrapper_robotinterface_command_velocity(qd)                                                                               robotinterface_command_velocity(qd)
#define  wrapper_robotinterface_command_joint_position_velocity_acceleration(joint, q, qd)                                         robotinterface_command_joint_position_velocity_acceleration(joint, q, qd)
#define  wrapper_robotinterface_command_velocity_security_torque_control_torque(qd, security_torque, control_torque, softness)     robotinterface_command_velocity_security_torque_control_torque(qd, security_torque, control_torque, softness)
#define  wrapper_robotinterface_command_torque(qd, security_torque, control_torque)                                                robotinterface_command_torque(qd, security_torque, control_torque)
#define  wrapper_robotinterface_command_empty_command()                                                                            robotinterface_command_empty_command()
#define  wrapper_robotinterface_master_goto_bootloader_mode()                                                                      robotinterface_master_goto_bootloader_mode()
#define  wrapper_robotinterface_command_digital_out_port(port, value)                                                              robotinterface_command_digital_out_port(port, value)
#define  wrapper_robotinterface_command_digital_out_bits(bits)                                                                     robotinterface_command_digital_out_bits(bits)
#define  wrapper_robotinterface_command_analog_out_port(port, value)                                                               robotinterface_command_analog_out_port(port, value)
#define  wrapper_robotinterface_command_analog_input_range_port(port, range)                                                       robotinterface_command_analog_input_range_port(port, range)
#define  wrapper_robotinterface_command_analog_output_domain(port, type)                                                           robotinterface_command_analog_output_domain(port, type)
#define  wrapper_robotinterface_command_tool_output_voltage(value)                                                                 robotinterface_command_tool_output_voltage(value)
#define  wrapper_robotinterface_set_tcp(tcp_pose)                                                                                  robotinterface_set_tcp(tcp_pose)
#define  wrapper_robotinterface_set_tcp_payload_cog(tcp_payload_cog)                                                               robotinterface_set_tcp_payload_cog(tcp_payload_cog)
#define  wrapper_robotinterface_set_tcp_payload(tcp_payload)                                                                       robotinterface_set_tcp_payload(tcp_payload)
#define  wrapper_robotinterface_get_tcp(tcp_pose)                                                                                  robotinterface_get_tcp(tcp_pose)
#define  wrapper_robotinterface_get_tcp_payload_cog(tcp_pose)                                                                      robotinterface_get_tcp_payload_cog(tcp_pose)
#define  wrapper_robotinterface_get_tcp_payload()                                                                                  robotinterface_get_tcp_payload()
#define  wrapper_robotinterface_set_tcp_wrench(new_tcp_wrench, in_base_coord)                                                      robotinterface_set_tcp_wrench(new_tcp_wrench, in_base_coord)
#define  wrapper_robotinterface_get_tcp_wrench(gotten_tcp_wrench)                                                                  robotinterface_get_tcp_wrench(gotten_tcp_wrench)
#define  wrapper_robotinterface_is_tcp_wrench_in_base_coord()                                                                      robotinterface_is_tcp_wrench_in_base_coord()
#define  wrapper_robotinterface_open(open_simulated)                                                                               robotinterface_open(open_simulated)
#define  wrapper_robotinterface_do_open(open_simulated)                                                                            robotinterface_do_open(open_simulated)
#define  wrapper_robotinterface_open_allow_bootloader(open_simulated)                                                              robotinterface_open_allow_bootloader(open_simulated)
#define  wrapper_robotinterface_read_state_blocking()                                                                              robotinterface_read_state_blocking()
#define  wrapper_robotinterface_send()                                                                                             robotinterface_send()
#define  wrapper_robotinterface_is_robot_connected()                                                                               robotinterface_is_robot_connected()
#define  wrapper_robotinterface_close()                                                                                            robotinterface_close()
#define  wrapper_robotinterface_get_robot_mode()                                                                                   robotinterface_get_robot_mode()
#define  wrapper_robotinterface_set_robot_ready_mode()                                                                             robotinterface_set_robot_ready_mode()
#define  wrapper_robotinterface_set_robot_running_mode()                                                                           robotinterface_set_robot_running_mode()
#define  wrapper_robotinterface_set_robot_freedrive_mode()                                                                         robotinterface_set_robot_freedrive_mode()
#define  wrapper_robotinterface_get_joint_mode(joint)                                                                              robotinterface_get_joint_mode(joint)
#define  wrapper_robotinterface_get_tool_mode()                                                                                    robotinterface_get_tool_mode()
#define  wrapper_robotinterface_get_message_count()                                                                                robotinterface_get_message_count()
#define  wrapper_robotinterface_get_message(message)                                                                               robotinterface_get_message(message)
#define  wrapper_robotinterface_get_message_codes(msg, error_code, error_argument)                                                 robotinterface_get_message_codes(msg, error_code, error_argument)
#define  wrapper_robotinterface_power_on_robot()                                                                                   robotinterface_power_on_robot()
#define  wrapper_robotinterface_power_off_robot()                                                                                  robotinterface_power_off_robot()
#define  wrapper_robotinterface_security_stop(joint_code, error_state, error_argument)                                             robotinterface_security_stop(joint_code, error_state, error_argument)
#define  wrapper_robotinterface_is_power_on_robot()                                                                                robotinterface_is_power_on_robot()
#define  wrapper_robotinterface_is_security_stopped()                                                                              robotinterface_is_security_stopped()
#define  wrapper_robotinterface_is_emergency_stopped()                                                                             robotinterface_is_emergency_stopped()
#define  wrapper_robotinterface_is_extra_button_pressed()                                                                          robotinterface_is_extra_button_pressed()
#define  wrapper_robotinterface_is_power_button_pressed()                                                                          robotinterface_is_power_button_pressed()
#define  wrapper_robotinterface_is_safety_signal_such_that_we_should_stop()                                                        robotinterface_is_safety_signal_such_that_we_should_stop()
#define  wrapper_robotinterface_unlock_security_stop()                                                                             robotinterface_unlock_security_stop()
#define  wrapper_robotinterface_has_security_message()                                                                             robotinterface_has_security_message()
#define  wrapper_robotinterface_get_security_message(message, error_state, error_argument)                                         robotinterface_get_security_message(message, error_state, error_argument)
#define  wrapper_robotinterface_get_master_control_bits()                                                                          robotinterface_get_master_control_bits()
#define  wrapper_robotinterface_get_actual(q, qd)                                                                                  robotinterface_get_actual(q, qd)
#define  wrapper_robotinterface_get_actual_position(q)                                                                             robotinterface_get_actual_position(q)
#define  wrapper_robotinterface_get_actual_velocity(qd)                                                                            robotinterface_get_actual_velocity(qd)
#define  wrapper_robotinterface_get_actual_current(I)                                                                              robotinterface_get_actual_current(I)
#define  wrapper_robotinterface_get_tool_accelerometer_readings(ax, ay, az)                                                        robotinterface_get_tool_accelerometer_readings(ax, ay, az)
#define  wrapper_robotinterface_get_tcp_force_scalar()                                                                             robotinterface_get_tcp_force_scalar()
#define  wrapper_robotinterface_get_tcp_force(F)                                                                                   robotinterface_get_tcp_force(F)
#define  wrapper_robotinterface_get_tcp_speed(V)                                                                                   robotinterface_get_tcp_speed(V)
#define  wrapper_robotinterface_get_tcp_power()                                                                                    robotinterface_get_tcp_power()
#define  wrapper_robotinterface_get_power()                                                                                        robotinterface_get_power()
#define  wrapper_robotinterface_get_actual_digital_input(port)                                                                     robotinterface_get_actual_digital_input(port)
#define  wrapper_robotinterface_get_actual_digital_output(port)                                                                    robotinterface_get_actual_digital_output(port)
#define  wrapper_robotinterface_get_actual_digital_input_bits()                                                                    robotinterface_get_actual_digital_input_bits()
#define  wrapper_robotinterface_get_actual_digital_output_bits()                                                                   robotinterface_get_actual_digital_output_bits()
#define  wrapper_robotinterface_get_actual_analog_input(port)                                                                      robotinterface_get_actual_analog_input(port)
#define  wrapper_robotinterface_get_actual_analog_output(port)                                                                     robotinterface_get_actual_analog_output(port)
#define  wrapper_robotinterface_get_actual_analog_input_range(port)                                                                robotinterface_get_actual_analog_input_range(port)
#define  wrapper_robotinterface_get_actual_analog_output_domain(port)                                                              robotinterface_get_actual_analog_output_domain(port)
#define  wrapper_robotinterface_get_target(q, qd, qdd)                                                                             robotinterface_get_target(q, qd, qdd)
#define  wrapper_robotinterface_get_target_position(q)                                                                             robotinterface_get_target_position(q)
#define  wrapper_robotinterface_get_target_velocity(qd)                                                                            robotinterface_get_target_velocity(qd)
#define  wrapper_robotinterface_get_target_acceleration(qdd)                                                                       robotinterface_get_target_acceleration(qdd)
#define  wrapper_robotinterface_get_target_current(I)                                                                              robotinterface_get_target_current(I)
#define  wrapper_robotinterface_get_target_moment(m)                                                                               robotinterface_get_target_moment(m)
#define  wrapper_robotinterface_get_target_digital_output_bits()                                                                   robotinterface_get_target_digital_output_bits()
#define  wrapper_robotinterface_get_target_analog_output(port)                                                                     robotinterface_get_target_analog_output(port)
#define  wrapper_robotinterface_get_target_analog_input_range(port)                                                                robotinterface_get_target_analog_input_range(port)
#define  wrapper_robotinterface_get_target_analog_output_domain(port)                                                              robotinterface_get_target_analog_output_domain(port)
#define  wrapper_robotinterface_get_master_temperature()                                                                           robotinterface_get_master_temperature()
#define  wrapper_robotinterface_get_robot_voltage_48V()                                                                            robotinterface_get_robot_voltage_48V()
#define  wrapper_robotinterface_get_robot_current()                                                                                robotinterface_get_robot_current()
#define  wrapper_robotinterface_get_master_io_current()                                                                            robotinterface_get_master_io_current()
#define  wrapper_robotinterface_get_master_safety_state()                                                                          robotinterface_get_master_safety_state()
#define  wrapper_robotinterface_get_master_on_off_state()                                                                          robotinterface_get_master_on_off_state()
#define  wrapper_robotinterface_safely_remove_euromap67_hardware()                                                                 robotinterface_safely_remove_euromap67_hardware()
#define  wrapper_robotinterface_disable_teach_pendant_safety()                                                                     robotinterface_disable_teach_pendant_safety()
#define  wrapper_robotinterface_get_motor_temperature(T)                                                                           robotinterface_get_motor_temperature(T)
#define  wrapper_robotinterface_get_micro_temperature(T)                                                                           robotinterface_get_micro_temperature(T)
#define  wrapper_robotinterface_get_joint_voltage(V)                                                                               robotinterface_get_joint_voltage(V)
#define  wrapper_robotinterface_get_tool_temperature()                                                                             robotinterface_get_tool_temperature()
#define  wrapper_robotinterface_get_tool_voltage_48V()                                                                             robotinterface_get_tool_voltage_48V()
#define  wrapper_robotinterface_get_tool_output_voltage()                                                                          robotinterface_get_tool_output_voltage()
#define  wrapper_robotinterface_get_tool_current()                                                                                 robotinterface_get_tool_current()
#define  wrapper_robotinterface_is_euromap_hardware_installed()                                                                    robotinterface_is_euromap_hardware_installed()
#define  wrapper_robotinterface_get_euromap_input(input_bit_number)                                                                robotinterface_get_euromap_input(input_bit_number)
#define  wrapper_robotinterface_get_euromap_output(output_bit_number)                                                              robotinterface_get_euromap_output(output_bit_number)
#define  wrapper_robotinterface_set_euromap_output(output_bit_number, desired_value)                                               robotinterface_set_euromap_output(output_bit_number, desired_value)
#define  wrapper_robotinterface_get_euromap_input_bits()                                                                           robotinterface_get_euromap_input_bits()
#define  wrapper_robotinterface_get_euromap_output_bits()                                                                          robotinterface_get_euromap_output_bits()
#define  wrapper_robotinterface_get_euromap_24V_voltage()                                                                          robotinterface_get_euromap_24V_voltage()
#define  wrapper_robotinterface_get_euromap_24V_current()                                                                          robotinterface_get_euromap_24V_current()
#define  wrapper_robotinterface_get_general_purpose_register(address)                                                              robotinterface_get_general_purpose_register(address)
#define  wrapper_robotinterface_set_general_purpose_register(address, value)                                                       robotinterface_set_general_purpose_register(address, value)
#define  wrapper_robotinterface_send_joint_regulation_parameter(joint_id, param_id, param_value)                                   robotinterface_send_joint_regulation_parameter(joint_id, param_id, param_value)
#define  wrapper_robotinterface_send_joint_special_parameter(joint_id, param_id, param_value)                                      robotinterface_send_joint_special_parameter(joint_id, param_id, param_value)
#else
/******************************build with fake robotinterface functions******************************/
#include "urrobot/ur5/control_box_driver/RobotinterfaceFake.h"

#define  wrapper_robotinterface_get_step()                                                                                         fake_robotinterface_get_step()
#define  wrapper_robotinterface_get_time()                                                                                         fake_robotinterface_get_time()
#define  wrapper_robotinterface_get_time_per_step()                                                                                fake_robotinterface_get_time_per_step()
#define  wrapper_robotinterface_command_position_velocity_acceleration(q, qd, qdd)                                                 fake_robotinterface_command_position_velocity_acceleration(q, qd, qdd)
#define  wrapper_robotinterface_command_velocity_acceleration(q, qd, qdd)                                                          fake_robotinterface_command_velocity_acceleration(q, qd, qdd)
#define  wrapper_robotinterface_command_velocity(qd)                                                                               fake_robotinterface_command_velocity(qd)
#define  wrapper_robotinterface_command_joint_position_velocity_acceleration(joint, q, qd)                                         fake_robotinterface_command_joint_position_velocity_acceleration(joint, q, qd)
#define  wrapper_robotinterface_command_velocity_security_torque_control_torque(qd, security_torque, control_torque, softness)     fake_robotinterface_command_velocity_security_torque_control_torque(qd, security_torque, control_torque, softness)
#define  wrapper_robotinterface_command_torque(qd, security_torque, control_torque)                                                fake_robotinterface_command_torque(qd, security_torque, control_torque)
#define  wrapper_robotinterface_command_empty_command()                                                                            fake_robotinterface_command_empty_command()
#define  wrapper_robotinterface_master_goto_bootloader_mode()                                                                      fake_robotinterface_master_goto_bootloader_mode()
#define  wrapper_robotinterface_command_digital_out_port(port, value)                                                              fake_robotinterface_command_digital_out_port(port, value)
#define  wrapper_robotinterface_command_digital_out_bits(bits)                                                                     fake_robotinterface_command_digital_out_bits(bits)
#define  wrapper_robotinterface_command_analog_out_port(port, value)                                                               fake_robotinterface_command_analog_out_port(port, value)
#define  wrapper_robotinterface_command_analog_input_range_port(port, range)                                                       fake_robotinterface_command_analog_input_range_port(port, range)
#define  wrapper_robotinterface_command_analog_output_domain(port, type)                                                           fake_robotinterface_command_analog_output_domain(port, type)
#define  wrapper_robotinterface_command_tool_output_voltage(value)                                                                 fake_robotinterface_command_tool_output_voltage(value)
#define  wrapper_robotinterface_set_tcp(tcp_pose)                                                                                  fake_robotinterface_set_tcp(tcp_pose)
#define  wrapper_robotinterface_set_tcp_payload_cog(tcp_payload_cog)                                                               fake_robotinterface_set_tcp_payload_cog(tcp_payload_cog)
#define  wrapper_robotinterface_set_tcp_payload(tcp_payload)                                                                       fake_robotinterface_set_tcp_payload(tcp_payload)
#define  wrapper_robotinterface_get_tcp(tcp_pose)                                                                                  fake_robotinterface_get_tcp(tcp_pose)
#define  wrapper_robotinterface_get_tcp_payload_cog(tcp_pose)                                                                      fake_robotinterface_get_tcp_payload_cog(tcp_pose)
#define  wrapper_robotinterface_get_tcp_payload()                                                                                  fake_robotinterface_get_tcp_payload()
#define  wrapper_robotinterface_set_tcp_wrench(new_tcp_wrench, in_base_coord)                                                      fake_robotinterface_set_tcp_wrench(new_tcp_wrench, in_base_coord)
#define  wrapper_robotinterface_get_tcp_wrench(gotten_tcp_wrench)                                                                  fake_robotinterface_get_tcp_wrench(gotten_tcp_wrench)
#define  wrapper_robotinterface_is_tcp_wrench_in_base_coord()                                                                      fake_robotinterface_is_tcp_wrench_in_base_coord()
#define  wrapper_robotinterface_open(open_simulated)                                                                               fake_robotinterface_open(open_simulated)
#define  wrapper_robotinterface_do_open(open_simulated)                                                                            fake_robotinterface_do_open(open_simulated)
#define  wrapper_robotinterface_open_allow_bootloader(open_simulated)                                                              fake_robotinterface_open_allow_bootloader(open_simulated)
#define  wrapper_robotinterface_read_state_blocking()                                                                              fake_robotinterface_read_state_blocking()
#define  wrapper_robotinterface_send()                                                                                             fake_robotinterface_send()
#define  wrapper_robotinterface_is_robot_connected()                                                                               fake_robotinterface_is_robot_connected()
#define  wrapper_robotinterface_close()                                                                                            fake_robotinterface_close()
#define  wrapper_robotinterface_get_robot_mode()                                                                                   fake_robotinterface_get_robot_mode()
#define  wrapper_robotinterface_set_robot_ready_mode()                                                                             fake_robotinterface_set_robot_ready_mode()
#define  wrapper_robotinterface_set_robot_running_mode()                                                                           fake_robotinterface_set_robot_running_mode()
#define  wrapper_robotinterface_set_robot_freedrive_mode()                                                                         fake_robotinterface_set_robot_freedrive_mode()
#define  wrapper_robotinterface_get_joint_mode(joint)                                                                              fake_robotinterface_get_joint_mode(joint)
#define  wrapper_robotinterface_get_tool_mode()                                                                                    fake_robotinterface_get_tool_mode()
#define  wrapper_robotinterface_get_message_count()                                                                                fake_robotinterface_get_message_count()
#define  wrapper_robotinterface_get_message(message)                                                                               fake_robotinterface_get_message(message)
#define  wrapper_robotinterface_get_message_codes(msg, error_code, error_argument)                                                 fake_robotinterface_get_message_codes(msg, error_code, error_argument)
#define  wrapper_robotinterface_power_on_robot()                                                                                   fake_robotinterface_power_on_robot()
#define  wrapper_robotinterface_power_off_robot()                                                                                  fake_robotinterface_power_off_robot()
#define  wrapper_robotinterface_security_stop(joint_code, error_state, error_argument)                                             fake_robotinterface_security_stop(joint_code, error_state, error_argument)
#define  wrapper_robotinterface_is_power_on_robot()                                                                                fake_robotinterface_is_power_on_robot()
#define  wrapper_robotinterface_is_security_stopped()                                                                              fake_robotinterface_is_security_stopped()
#define  wrapper_robotinterface_is_emergency_stopped()                                                                             fake_robotinterface_is_emergency_stopped()
#define  wrapper_robotinterface_is_extra_button_pressed()                                                                          fake_robotinterface_is_extra_button_pressed()
#define  wrapper_robotinterface_is_power_button_pressed()                                                                          fake_robotinterface_is_power_button_pressed()
#define  wrapper_robotinterface_is_safety_signal_such_that_we_should_stop()                                                        fake_robotinterface_is_safety_signal_such_that_we_should_stop()
#define  wrapper_robotinterface_unlock_security_stop()                                                                             fake_robotinterface_unlock_security_stop()
#define  wrapper_robotinterface_has_security_message()                                                                             fake_robotinterface_has_security_message()
#define  wrapper_robotinterface_get_security_message(message, error_state, error_argument)                                         fake_robotinterface_get_security_message(message, error_state, error_argument)
#define  wrapper_robotinterface_get_master_control_bits()                                                                          fake_robotinterface_get_master_control_bits()
#define  wrapper_robotinterface_get_actual(q, qd)                                                                                  fake_robotinterface_get_actual(q, qd)
#define  wrapper_robotinterface_get_actual_position(q)                                                                             fake_robotinterface_get_actual_position(q)
#define  wrapper_robotinterface_get_actual_velocity(qd)                                                                            fake_robotinterface_get_actual_velocity(qd)
#define  wrapper_robotinterface_get_actual_current(I)                                                                              fake_robotinterface_get_actual_current(I)
#define  wrapper_robotinterface_get_tool_accelerometer_readings(ax, ay, az)                                                        fake_robotinterface_get_tool_accelerometer_readings(ax, ay, az)
#define  wrapper_robotinterface_get_tcp_force_scalar()                                                                             fake_robotinterface_get_tcp_force_scalar()
#define  wrapper_robotinterface_get_tcp_force(F)                                                                                   fake_robotinterface_get_tcp_force(F)
#define  wrapper_robotinterface_get_tcp_speed(V)                                                                                   fake_robotinterface_get_tcp_speed(V)
#define  wrapper_robotinterface_get_tcp_power()                                                                                    fake_robotinterface_get_tcp_power()
#define  wrapper_robotinterface_get_power()                                                                                        fake_robotinterface_get_power()
#define  wrapper_robotinterface_get_actual_digital_input(port)                                                                     fake_robotinterface_get_actual_digital_input(port)
#define  wrapper_robotinterface_get_actual_digital_output(port)                                                                    fake_robotinterface_get_actual_digital_output(port)
#define  wrapper_robotinterface_get_actual_digital_input_bits()                                                                    fake_robotinterface_get_actual_digital_input_bits()
#define  wrapper_robotinterface_get_actual_digital_output_bits()                                                                   fake_robotinterface_get_actual_digital_output_bits()
#define  wrapper_robotinterface_get_actual_analog_input(port)                                                                      fake_robotinterface_get_actual_analog_input(port)
#define  wrapper_robotinterface_get_actual_analog_output(port)                                                                     fake_robotinterface_get_actual_analog_output(port)
#define  wrapper_robotinterface_get_actual_analog_input_range(port)                                                                fake_robotinterface_get_actual_analog_input_range(port)
#define  wrapper_robotinterface_get_actual_analog_output_domain(port)                                                              fake_robotinterface_get_actual_analog_output_domain(port)
#define  wrapper_robotinterface_get_target(q, qd, qdd)                                                                             fake_robotinterface_get_target(q, qd, qdd)
#define  wrapper_robotinterface_get_target_position(q)                                                                             fake_robotinterface_get_target_position(q)
#define  wrapper_robotinterface_get_target_velocity(qd)                                                                            fake_robotinterface_get_target_velocity(qd)
#define  wrapper_robotinterface_get_target_acceleration(qdd)                                                                       fake_robotinterface_get_target_acceleration(qdd)
#define  wrapper_robotinterface_get_target_current(I)                                                                              fake_robotinterface_get_target_current(I)
#define  wrapper_robotinterface_get_target_moment(m)                                                                               fake_robotinterface_get_target_moment(m)
#define  wrapper_robotinterface_get_target_digital_output_bits()                                                                   fake_robotinterface_get_target_digital_output_bits()
#define  wrapper_robotinterface_get_target_analog_output(port)                                                                     fake_robotinterface_get_target_analog_output(port)
#define  wrapper_robotinterface_get_target_analog_input_range(port)                                                                fake_robotinterface_get_target_analog_input_range(port)
#define  wrapper_robotinterface_get_target_analog_output_domain(port)                                                              fake_robotinterface_get_target_analog_output_domain(port)
#define  wrapper_robotinterface_get_master_temperature()                                                                           fake_robotinterface_get_master_temperature()
#define  wrapper_robotinterface_get_robot_voltage_48V()                                                                            fake_robotinterface_get_robot_voltage_48V()
#define  wrapper_robotinterface_get_robot_current()                                                                                fake_robotinterface_get_robot_current()
#define  wrapper_robotinterface_get_master_io_current()                                                                            fake_robotinterface_get_master_io_current()
#define  wrapper_robotinterface_get_master_safety_state()                                                                          fake_robotinterface_get_master_safety_state()
#define  wrapper_robotinterface_get_master_on_off_state()                                                                          fake_robotinterface_get_master_on_off_state()
#define  wrapper_robotinterface_safely_remove_euromap67_hardware()                                                                 fake_robotinterface_safely_remove_euromap67_hardware()
#define  wrapper_robotinterface_disable_teach_pendant_safety()                                                                     fake_robotinterface_disable_teach_pendant_safety()
#define  wrapper_robotinterface_get_motor_temperature(T)                                                                           fake_robotinterface_get_motor_temperature(T)
#define  wrapper_robotinterface_get_micro_temperature(T)                                                                           fake_robotinterface_get_micro_temperature(T)
#define  wrapper_robotinterface_get_joint_voltage(V)                                                                               fake_robotinterface_get_joint_voltage(V)
#define  wrapper_robotinterface_get_tool_temperature()                                                                             fake_robotinterface_get_tool_temperature()
#define  wrapper_robotinterface_get_tool_voltage_48V()                                                                             fake_robotinterface_get_tool_voltage_48V()
#define  wrapper_robotinterface_get_tool_output_voltage()                                                                          fake_robotinterface_get_tool_output_voltage()
#define  wrapper_robotinterface_get_tool_current()                                                                                 fake_robotinterface_get_tool_current()
#define  wrapper_robotinterface_is_euromap_hardware_installed()                                                                    fake_robotinterface_is_euromap_hardware_installed()
#define  wrapper_robotinterface_get_euromap_input(input_bit_number)                                                                fake_robotinterface_get_euromap_input(input_bit_number)
#define  wrapper_robotinterface_get_euromap_output(output_bit_number)                                                              fake_robotinterface_get_euromap_output(output_bit_number)
#define  wrapper_robotinterface_set_euromap_output(output_bit_number, desired_value)                                               fake_robotinterface_set_euromap_output(output_bit_number, desired_value)
#define  wrapper_robotinterface_get_euromap_input_bits()                                                                           fake_robotinterface_get_euromap_input_bits()
#define  wrapper_robotinterface_get_euromap_output_bits()                                                                          fake_robotinterface_get_euromap_output_bits()
#define  wrapper_robotinterface_get_euromap_24V_voltage()                                                                          fake_robotinterface_get_euromap_24V_voltage()
#define  wrapper_robotinterface_get_euromap_24V_current()                                                                          fake_robotinterface_get_euromap_24V_current()
#define  wrapper_robotinterface_get_general_purpose_register(address)                                                              fake_robotinterface_get_general_purpose_register(address)
#define  wrapper_robotinterface_set_general_purpose_register(address, value)                                                       fake_robotinterface_set_general_purpose_register(address, value)
#define  wrapper_robotinterface_send_joint_regulation_parameter(joint_id, param_id, param_value)                                   fake_robotinterface_send_joint_regulation_parameter(joint_id, param_id, param_value)
#define  wrapper_robotinterface_send_joint_special_parameter(joint_id, param_id, param_value)                                      fake_robotinterface_send_joint_special_parameter(joint_id, param_id, param_value)
#endif

#endif